[(call TFAR_fnc_activeLrRadio), 1, "66"] call TFAR_fnc_SetChannelFrequency;
[(call TFAR_fnc_activeLrRadio), 2, "66"] call TFAR_fnc_SetChannelFrequency;
[(call TFAR_fnc_activeLrRadio), 3, "66"] call TFAR_fnc_SetChannelFrequency;
[(call TFAR_fnc_activeLrRadio), 4, "66"] call TFAR_fnc_SetChannelFrequency;
[(call TFAR_fnc_activeLrRadio), 5, "66"] call TFAR_fnc_SetChannelFrequency;
[(call TFAR_fnc_activeLrRadio), 6, "66"] call TFAR_fnc_SetChannelFrequency;
[(call TFAR_fnc_activeLrRadio), 7, "66"] call TFAR_fnc_SetChannelFrequency;
[(call TFAR_fnc_activeLrRadio), 8, "66"] call TFAR_fnc_SetChannelFrequency;
[(call TFAR_fnc_activeLrRadio), 9, "66"] call TFAR_fnc_SetChannelFrequency;
[(call TFAR_fnc_activeLrRadio), 2] call TFAR_fnc_setLrStereo;